version: '2'

services:
  reverseproxy:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:8080
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf.d:/etc/nginx/nginx.conf.d
